name: Local Test

on:
  workflow_dispatch:
    inputs:
      scenario:
        description: 'Scenario to run'
        required: true
        default: '[Web] Sell From Real with auto rejection lower limit'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        run: |
          echo "Using local code instead of checking out"
          
      - name: Setup Node.js
        run: |
          echo "Setting up Node.js"
          # Install Node.js
          curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
          apt-get install -y nodejs
          node --version
          npm --version
          
      - name: Install dependencies
        run: |
          echo "Installing dependencies"
          npm ci
          
      - name: Install Playwright Browsers
        run: |
          echo "Installing Playwright browsers"
          npx playwright install --with-deps chromium
          
      - name: Run specific feature scenario
        run: |
          # Use a simpler approach to get the scenario name
          if [ -n "$SCENARIO_NAME" ]; then
            SCENARIO_TO_RUN="$SCENARIO_NAME"
          else
            SCENARIO_TO_RUN="${{ github.event.inputs.scenario || '[Web] Sell From Real with auto rejection lower limit' }}"
          fi
          echo "Running scenario: $SCENARIO_TO_RUN"
          
          # Debug: List feature files
          echo "Available feature files:"
          find src/features -name "*.feature" -type f
          
          # Debug: Show feature file content
          echo "Content of login.feature:"
          cat src/features/login.feature
          
          # Run without name filter first to see all scenarios
          echo "Running all scenarios to debug:"
          npx cucumber-js --require src/step-definitions/*.ts --require src/support/*.ts src/features/login.feature --tags "@web"
          
          # Now run with name filter
          echo "Running specific scenario:"
          npx cucumber-js --require src/step-definitions/*.ts --require src/support/*.ts src/features/login.feature --tags "@web" --name "$SCENARIO_TO_RUN"
          
      - name: Save test results
        if: always()
        run: |
          mkdir -p artifacts/cucumber-report
          cp cucumber-report.html artifacts/cucumber-report/ || echo "No cucumber report found"
          
          mkdir -p artifacts/playwright-videos
          cp -r videos/* artifacts/playwright-videos/ 2>/dev/null || echo "No videos found"
          
          mkdir -p artifacts/playwright-screenshots
          cp -r screenshots/* artifacts/playwright-screenshots/ 2>/dev/null || echo "No screenshots found" 